openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost/v1
paths:
  /:
    get:
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                enum: ["Hello world!"]
    post:
      responses:
        200:
          content:
            application/json:
